### ISSUE TITLE
System.ArgumentException: The fetched Response is no A2S_INFO Response.

### ISSUE THREAD

**Issue by tuple789** [Florian2406/Okolni-Source-Ouery#6]
Using your library for the first time today, and this is basically the code from your GitHub page Demo but with different server ip:

            IQueryConnection conn = new QueryConnection();

            conn.Host = "198.244.176.54";  // TF2 server
            conn.Port = 27015;

            conn.Connect(); // Create the initial connection

            var info = conn.GetInfo(); // Get the Server info
            var players = conn.GetPlayers(); // Get the Player info
            var rules = conn.GetRules(); // Get the Rules

            Console.WriteLine($"Server info: {info.ToString()}");
            Console.WriteLine($"Current players: {string.Join("; ", players.Players.Select(p => p.Name))}");
            Console.WriteLine($"Rules: {string.Join("; ", rules.Rules.Select(r => $"{r.Key}: {r.Value}"))}");

I get this error:

Unhandled exception. Okolni.Source.Common.SourceQueryException: Could not gather Info
 ---> System.ArgumentException: The fetched Response is no A2S_INFO Response.
   at Okolni.Source.Query.QueryConnection.GetInfo()
   --- End of inner exception stack trace ---
   at Okolni.Source.Query.QueryConnection.GetInfo()
   at AS2_Steam_Test.Program.NewLibraryTest() in D:\PROGRAMS\VISUAL_STUDIO\AS2_Steam_Test\Program.cs:line 108
   at AS2_Steam_Test.Program.Main(String[] args) in D:\PROGRAMS\VISUAL_STUDIO\AS2_Steam_Test\Program.cs:line 16

Could this be related to a recent update to Team Fortress 2 which forces server to use challenge=1 for AS2_Info?:
https://steamcommunity.com/discussions/forum/14/2974028351344359625/

**Comment by Florian2406** [comment]
I will have a look at the issue

**Comment by Florian2406** [comment]
I tested the responses returned from the server and the issue actually is what you described too.
I will implement a fix for the challenge requests/responses and update this issue.

**Comment by Florian2406** [comment]
Fixed in Release #9 

I also implemented multi packet response as the rules request to your server returned a multi packet response. So all three requests work for your server now. The package is now also available on nuget.org.
